#pragma once
// Default shader vertex attribute locations
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION    0
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD    1
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL      2
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR       3
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT     4
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2   5
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_INDICES     6
#if defined(RL_SUPPORT_MESH_GPU_SKINNING)
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEIDS     7
#define PL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEWEIGHTS 8
#endif